---
- name: Install net-tools on Test Server
  hosts: test-servers
  become: true
  remote_user: ubuntu   # Specify the SSH username to connect to the server

  tasks:
    - name: Install net-tools package
      apt:
        name: net-tools
        state: present
